name: "create-react-app"
description: "create-react-app github action"
author: "Rik Hoffbauer"
inputs:
    myInput: # change this
        description: "input description here"
        default: "default value if applicable"
runs:
    using: "node12"
    main: "lib/index.js"
